name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python modelCode.py
        
          cat metrics.txt >> report.md
          echo "![](out.png)" >> report.md
          cml comment create report.md 
