name: rent-price-pred-model
on: [push]
jobs:
  run:
    runs-on:[ubuntu-latest]
    steps:
      - users: actions/checkout@v2
      - name: cml_run
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python modelCode.py
          
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data viz" >> report.md
          cml-publish out.png --md >> report.md
          
          cml-send-comment report.md
